source 'https://rubygems.org'

ruby '2.1.2'

gem 'github-pages'      , '22'
gem 'rake'
gem 'foreman'           , '= 0.63.0'
gem 'guard-compass'     , '0.0.8'
gem 'sass'              , '= 3.2.14'
gem 'rspec'             , '~> 2.14.1'
gem 'pry'               , '~> 0.9.12.6'
gem 'nokogiri'          , '~> 1.6.1'
gem 'vcr'               , '~> 2.8.0'
gem 'webmock'           , '< 1.16'
gem 'i18n'              , '~> 0.6.9'
gem 'colored'           , '~> 1.2'
gem "compass"           , '= 0.12.3'
